batch_size: 32
context_length: 30
dataset: tumor_growth
device: cuda:0
diffusion_config: diffusion_small_config
do_final_eval: true
eval_every: 10
freq: D
gradient_clip_val: 0.5
init_skip: false
lr: 0.001
max_epochs: 200
model: conditional
noise_observed: true
normalization: mean
num_batches_per_epoch: 128
prediction_length: 14
setup: forecasting
use_features: false
use_lags: true
use_validation_set: true
